# coding: utf-8

"""
    Refinery Calc API Documentation

    Integrate the powerful Refinery Calc Engine into your process using this API.  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@refinerycalc.com.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import refinerycalc
from refinerycalc.models.schedule_simulation_request_model import ScheduleSimulationRequestModel  # noqa: E501
from refinerycalc.rest import ApiException


class TestScheduleSimulationRequestModel(unittest.TestCase):
    """ScheduleSimulationRequestModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testScheduleSimulationRequestModel(self):
        """Test ScheduleSimulationRequestModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = refinerycalc.models.schedule_simulation_request_model.ScheduleSimulationRequestModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
