# coding: utf-8

"""
    Refinery Calc API Documentation

    Integrate the powerful Refinery Calc Engine into your process using this API.  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@refinerycalc.com.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import refinerycalc
from refinerycalc.api.product_prices_api import ProductPricesApi  # noqa: E501
from refinerycalc.rest import ApiException


class TestProductPricesApi(unittest.TestCase):
    """ProductPricesApi unit test stubs"""

    def setUp(self):
        self.api = ProductPricesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v1_product_prices_get(self):
        """Test case for v1_product_prices_get

        Returns product price list  # noqa: E501
        """
        pass

    def test_v1_product_prices_id_get(self):
        """Test case for v1_product_prices_id_get

        Get product price by id  # noqa: E501
        """
        pass

    def test_v1_product_prices_region_id_get(self):
        """Test case for v1_product_prices_region_id_get

        Get product price by region id  # noqa: E501
        """
        pass

    def test_v1_product_prices_region_region_name_get(self):
        """Test case for v1_product_prices_region_region_name_get

        Get product price by region  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
