# coding: utf-8

"""
    Refinery Calc API Documentation

    Integrate the powerful Refinery Calc Engine into your process using this API.  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@refinerycalc.com.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import refinerycalc
from refinerycalc.models.refinery_unit_model import RefineryUnitModel  # noqa: E501
from refinerycalc.rest import ApiException


class TestRefineryUnitModel(unittest.TestCase):
    """RefineryUnitModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRefineryUnitModel(self):
        """Test RefineryUnitModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = refinerycalc.models.refinery_unit_model.RefineryUnitModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
