# coding: utf-8

"""
    Refinery Calc API Documentation

    Integrate the powerful Refinery Calc Engine into your process using this API.  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@refinerycalc.com.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import refinerycalc
from refinerycalc.models.refinery_change_kero_mode import RefineryChangeKeroMode  # noqa: E501
from refinerycalc.rest import ApiException


class TestRefineryChangeKeroMode(unittest.TestCase):
    """RefineryChangeKeroMode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRefineryChangeKeroMode(self):
        """Test RefineryChangeKeroMode"""
        # FIXME: construct object with mandatory attributes with example values
        # model = refinerycalc.models.refinery_change_kero_mode.RefineryChangeKeroMode()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
