# coding: utf-8

"""
    Refinery Calc API Documentation

    Integrate the powerful Refinery Calc Engine into your process using this API.  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@refinerycalc.com.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CreateSimulationResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'success': 'bool',
        'message': 'str',
        'simulation_id': 'str'
    }

    attribute_map = {
        'success': 'success',
        'message': 'message',
        'simulation_id': 'simulationId'
    }

    def __init__(self, success=None, message=None, simulation_id=None):  # noqa: E501
        """CreateSimulationResponse - a model defined in Swagger"""  # noqa: E501
        self._success = None
        self._message = None
        self._simulation_id = None
        self.discriminator = None
        if success is not None:
            self.success = success
        if message is not None:
            self.message = message
        if simulation_id is not None:
            self.simulation_id = simulation_id

    @property
    def success(self):
        """Gets the success of this CreateSimulationResponse.  # noqa: E501


        :return: The success of this CreateSimulationResponse.  # noqa: E501
        :rtype: bool
        """
        return self._success

    @success.setter
    def success(self, success):
        """Sets the success of this CreateSimulationResponse.


        :param success: The success of this CreateSimulationResponse.  # noqa: E501
        :type: bool
        """

        self._success = success

    @property
    def message(self):
        """Gets the message of this CreateSimulationResponse.  # noqa: E501


        :return: The message of this CreateSimulationResponse.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this CreateSimulationResponse.


        :param message: The message of this CreateSimulationResponse.  # noqa: E501
        :type: str
        """

        self._message = message

    @property
    def simulation_id(self):
        """Gets the simulation_id of this CreateSimulationResponse.  # noqa: E501


        :return: The simulation_id of this CreateSimulationResponse.  # noqa: E501
        :rtype: str
        """
        return self._simulation_id

    @simulation_id.setter
    def simulation_id(self, simulation_id):
        """Sets the simulation_id of this CreateSimulationResponse.


        :param simulation_id: The simulation_id of this CreateSimulationResponse.  # noqa: E501
        :type: str
        """

        self._simulation_id = simulation_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreateSimulationResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateSimulationResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
