# coding: utf-8

"""
    Refinery Calc API Documentation

    Integrate the powerful Refinery Calc Engine into your process using this API.  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@refinerycalc.com.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CrudePrice(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'crude_id': 'int',
        'price': 'float',
        'freight': 'float'
    }

    attribute_map = {
        'crude_id': 'crudeId',
        'price': 'price',
        'freight': 'freight'
    }

    def __init__(self, crude_id=None, price=None, freight=None):  # noqa: E501
        """CrudePrice - a model defined in Swagger"""  # noqa: E501
        self._crude_id = None
        self._price = None
        self._freight = None
        self.discriminator = None
        if crude_id is not None:
            self.crude_id = crude_id
        if price is not None:
            self.price = price
        if freight is not None:
            self.freight = freight

    @property
    def crude_id(self):
        """Gets the crude_id of this CrudePrice.  # noqa: E501


        :return: The crude_id of this CrudePrice.  # noqa: E501
        :rtype: int
        """
        return self._crude_id

    @crude_id.setter
    def crude_id(self, crude_id):
        """Sets the crude_id of this CrudePrice.


        :param crude_id: The crude_id of this CrudePrice.  # noqa: E501
        :type: int
        """

        self._crude_id = crude_id

    @property
    def price(self):
        """Gets the price of this CrudePrice.  # noqa: E501


        :return: The price of this CrudePrice.  # noqa: E501
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this CrudePrice.


        :param price: The price of this CrudePrice.  # noqa: E501
        :type: float
        """

        self._price = price

    @property
    def freight(self):
        """Gets the freight of this CrudePrice.  # noqa: E501


        :return: The freight of this CrudePrice.  # noqa: E501
        :rtype: float
        """
        return self._freight

    @freight.setter
    def freight(self, freight):
        """Sets the freight of this CrudePrice.


        :param freight: The freight of this CrudePrice.  # noqa: E501
        :type: float
        """

        self._freight = freight

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CrudePrice, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CrudePrice):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
