# coding: utf-8

"""
    Refinery Calc API Documentation

    Integrate the powerful Refinery Calc Engine into your process using this API.  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@refinerycalc.com.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Graph(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'label': 'str',
        'background_color': 'list[str]',
        'border_color': 'list[str]',
        'data': 'list[str]'
    }

    attribute_map = {
        'label': 'label',
        'background_color': 'backgroundColor',
        'border_color': 'borderColor',
        'data': 'data'
    }

    def __init__(self, label=None, background_color=None, border_color=None, data=None):  # noqa: E501
        """Graph - a model defined in Swagger"""  # noqa: E501
        self._label = None
        self._background_color = None
        self._border_color = None
        self._data = None
        self.discriminator = None
        if label is not None:
            self.label = label
        if background_color is not None:
            self.background_color = background_color
        if border_color is not None:
            self.border_color = border_color
        if data is not None:
            self.data = data

    @property
    def label(self):
        """Gets the label of this Graph.  # noqa: E501


        :return: The label of this Graph.  # noqa: E501
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label):
        """Sets the label of this Graph.


        :param label: The label of this Graph.  # noqa: E501
        :type: str
        """

        self._label = label

    @property
    def background_color(self):
        """Gets the background_color of this Graph.  # noqa: E501


        :return: The background_color of this Graph.  # noqa: E501
        :rtype: list[str]
        """
        return self._background_color

    @background_color.setter
    def background_color(self, background_color):
        """Sets the background_color of this Graph.


        :param background_color: The background_color of this Graph.  # noqa: E501
        :type: list[str]
        """

        self._background_color = background_color

    @property
    def border_color(self):
        """Gets the border_color of this Graph.  # noqa: E501


        :return: The border_color of this Graph.  # noqa: E501
        :rtype: list[str]
        """
        return self._border_color

    @border_color.setter
    def border_color(self, border_color):
        """Sets the border_color of this Graph.


        :param border_color: The border_color of this Graph.  # noqa: E501
        :type: list[str]
        """

        self._border_color = border_color

    @property
    def data(self):
        """Gets the data of this Graph.  # noqa: E501


        :return: The data of this Graph.  # noqa: E501
        :rtype: list[str]
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this Graph.


        :param data: The data of this Graph.  # noqa: E501
        :type: list[str]
        """

        self._data = data

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Graph, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Graph):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
