# coding: utf-8

"""
    Refinery Calc API Documentation

    Integrate the powerful Refinery Calc Engine into your process using this API.  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@refinerycalc.com.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GraphModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'labels': 'list[str]',
        'datasets': 'list[Graph]'
    }

    attribute_map = {
        'type': 'type',
        'labels': 'labels',
        'datasets': 'datasets'
    }

    def __init__(self, type=None, labels=None, datasets=None):  # noqa: E501
        """GraphModel - a model defined in Swagger"""  # noqa: E501
        self._type = None
        self._labels = None
        self._datasets = None
        self.discriminator = None
        if type is not None:
            self.type = type
        if labels is not None:
            self.labels = labels
        if datasets is not None:
            self.datasets = datasets

    @property
    def type(self):
        """Gets the type of this GraphModel.  # noqa: E501


        :return: The type of this GraphModel.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this GraphModel.


        :param type: The type of this GraphModel.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def labels(self):
        """Gets the labels of this GraphModel.  # noqa: E501


        :return: The labels of this GraphModel.  # noqa: E501
        :rtype: list[str]
        """
        return self._labels

    @labels.setter
    def labels(self, labels):
        """Sets the labels of this GraphModel.


        :param labels: The labels of this GraphModel.  # noqa: E501
        :type: list[str]
        """

        self._labels = labels

    @property
    def datasets(self):
        """Gets the datasets of this GraphModel.  # noqa: E501


        :return: The datasets of this GraphModel.  # noqa: E501
        :rtype: list[Graph]
        """
        return self._datasets

    @datasets.setter
    def datasets(self, datasets):
        """Sets the datasets of this GraphModel.


        :param datasets: The datasets of this GraphModel.  # noqa: E501
        :type: list[Graph]
        """

        self._datasets = datasets

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GraphModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GraphModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
