# coding: utf-8

"""
    Refinery Calc API Documentation

    Integrate the powerful Refinery Calc Engine into your process using this API.  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@refinerycalc.com.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RefineryChangeKeroMode(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'refinery_id': 'int',
        'new_mode': 'KeroOptimizationMode',
        'value': 'float',
        'apply_all': 'bool'
    }

    attribute_map = {
        'refinery_id': 'refineryId',
        'new_mode': 'newMode',
        'value': 'value',
        'apply_all': 'applyAll'
    }

    def __init__(self, refinery_id=None, new_mode=None, value=None, apply_all=None):  # noqa: E501
        """RefineryChangeKeroMode - a model defined in Swagger"""  # noqa: E501
        self._refinery_id = None
        self._new_mode = None
        self._value = None
        self._apply_all = None
        self.discriminator = None
        if refinery_id is not None:
            self.refinery_id = refinery_id
        if new_mode is not None:
            self.new_mode = new_mode
        if value is not None:
            self.value = value
        if apply_all is not None:
            self.apply_all = apply_all

    @property
    def refinery_id(self):
        """Gets the refinery_id of this RefineryChangeKeroMode.  # noqa: E501


        :return: The refinery_id of this RefineryChangeKeroMode.  # noqa: E501
        :rtype: int
        """
        return self._refinery_id

    @refinery_id.setter
    def refinery_id(self, refinery_id):
        """Sets the refinery_id of this RefineryChangeKeroMode.


        :param refinery_id: The refinery_id of this RefineryChangeKeroMode.  # noqa: E501
        :type: int
        """

        self._refinery_id = refinery_id

    @property
    def new_mode(self):
        """Gets the new_mode of this RefineryChangeKeroMode.  # noqa: E501


        :return: The new_mode of this RefineryChangeKeroMode.  # noqa: E501
        :rtype: KeroOptimizationMode
        """
        return self._new_mode

    @new_mode.setter
    def new_mode(self, new_mode):
        """Sets the new_mode of this RefineryChangeKeroMode.


        :param new_mode: The new_mode of this RefineryChangeKeroMode.  # noqa: E501
        :type: KeroOptimizationMode
        """

        self._new_mode = new_mode

    @property
    def value(self):
        """Gets the value of this RefineryChangeKeroMode.  # noqa: E501


        :return: The value of this RefineryChangeKeroMode.  # noqa: E501
        :rtype: float
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this RefineryChangeKeroMode.


        :param value: The value of this RefineryChangeKeroMode.  # noqa: E501
        :type: float
        """

        self._value = value

    @property
    def apply_all(self):
        """Gets the apply_all of this RefineryChangeKeroMode.  # noqa: E501


        :return: The apply_all of this RefineryChangeKeroMode.  # noqa: E501
        :rtype: bool
        """
        return self._apply_all

    @apply_all.setter
    def apply_all(self, apply_all):
        """Sets the apply_all of this RefineryChangeKeroMode.


        :param apply_all: The apply_all of this RefineryChangeKeroMode.  # noqa: E501
        :type: bool
        """

        self._apply_all = apply_all

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RefineryChangeKeroMode, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RefineryChangeKeroMode):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
