# coding: utf-8

"""
    Refinery Calc API Documentation

    Integrate the powerful Refinery Calc Engine into your process using this API.  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@refinerycalc.com.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RefineryUnitReference(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'capacity': 'float',
        'bias': 'float',
        'is_shutdown': 'bool'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'capacity': 'capacity',
        'bias': 'bias',
        'is_shutdown': 'isShutdown'
    }

    def __init__(self, id=None, name=None, capacity=None, bias=None, is_shutdown=None):  # noqa: E501
        """RefineryUnitReference - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._capacity = None
        self._bias = None
        self._is_shutdown = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if capacity is not None:
            self.capacity = capacity
        if bias is not None:
            self.bias = bias
        if is_shutdown is not None:
            self.is_shutdown = is_shutdown

    @property
    def id(self):
        """Gets the id of this RefineryUnitReference.  # noqa: E501


        :return: The id of this RefineryUnitReference.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this RefineryUnitReference.


        :param id: The id of this RefineryUnitReference.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this RefineryUnitReference.  # noqa: E501


        :return: The name of this RefineryUnitReference.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this RefineryUnitReference.


        :param name: The name of this RefineryUnitReference.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def capacity(self):
        """Gets the capacity of this RefineryUnitReference.  # noqa: E501


        :return: The capacity of this RefineryUnitReference.  # noqa: E501
        :rtype: float
        """
        return self._capacity

    @capacity.setter
    def capacity(self, capacity):
        """Sets the capacity of this RefineryUnitReference.


        :param capacity: The capacity of this RefineryUnitReference.  # noqa: E501
        :type: float
        """

        self._capacity = capacity

    @property
    def bias(self):
        """Gets the bias of this RefineryUnitReference.  # noqa: E501


        :return: The bias of this RefineryUnitReference.  # noqa: E501
        :rtype: float
        """
        return self._bias

    @bias.setter
    def bias(self, bias):
        """Sets the bias of this RefineryUnitReference.


        :param bias: The bias of this RefineryUnitReference.  # noqa: E501
        :type: float
        """

        self._bias = bias

    @property
    def is_shutdown(self):
        """Gets the is_shutdown of this RefineryUnitReference.  # noqa: E501


        :return: The is_shutdown of this RefineryUnitReference.  # noqa: E501
        :rtype: bool
        """
        return self._is_shutdown

    @is_shutdown.setter
    def is_shutdown(self, is_shutdown):
        """Sets the is_shutdown of this RefineryUnitReference.


        :param is_shutdown: The is_shutdown of this RefineryUnitReference.  # noqa: E501
        :type: bool
        """

        self._is_shutdown = is_shutdown

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RefineryUnitReference, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RefineryUnitReference):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
