# coding: utf-8

"""
    Refinery Calc API Documentation

    Integrate the powerful Refinery Calc Engine into your process using this API.  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@refinerycalc.com.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SimulationResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'simulations': 'list[CalculatorModel]'
    }

    attribute_map = {
        'simulations': 'simulations'
    }

    def __init__(self, simulations=None):  # noqa: E501
        """SimulationResponse - a model defined in Swagger"""  # noqa: E501
        self._simulations = None
        self.discriminator = None
        if simulations is not None:
            self.simulations = simulations

    @property
    def simulations(self):
        """Gets the simulations of this SimulationResponse.  # noqa: E501


        :return: The simulations of this SimulationResponse.  # noqa: E501
        :rtype: list[CalculatorModel]
        """
        return self._simulations

    @simulations.setter
    def simulations(self, simulations):
        """Sets the simulations of this SimulationResponse.


        :param simulations: The simulations of this SimulationResponse.  # noqa: E501
        :type: list[CalculatorModel]
        """

        self._simulations = simulations

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SimulationResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SimulationResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
