# coding: utf-8

"""
    Refinery Calc API Documentation

    Integrate the powerful Refinery Calc Engine into your process using this API.  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@refinerycalc.com.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TimeseriesCrudeReference(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'percentage': 'float',
        'price': 'float'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'percentage': 'percentage',
        'price': 'price'
    }

    def __init__(self, id=None, name=None, percentage=None, price=None):  # noqa: E501
        """TimeseriesCrudeReference - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._percentage = None
        self._price = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if percentage is not None:
            self.percentage = percentage
        if price is not None:
            self.price = price

    @property
    def id(self):
        """Gets the id of this TimeseriesCrudeReference.  # noqa: E501


        :return: The id of this TimeseriesCrudeReference.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this TimeseriesCrudeReference.


        :param id: The id of this TimeseriesCrudeReference.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this TimeseriesCrudeReference.  # noqa: E501


        :return: The name of this TimeseriesCrudeReference.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this TimeseriesCrudeReference.


        :param name: The name of this TimeseriesCrudeReference.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def percentage(self):
        """Gets the percentage of this TimeseriesCrudeReference.  # noqa: E501


        :return: The percentage of this TimeseriesCrudeReference.  # noqa: E501
        :rtype: float
        """
        return self._percentage

    @percentage.setter
    def percentage(self, percentage):
        """Sets the percentage of this TimeseriesCrudeReference.


        :param percentage: The percentage of this TimeseriesCrudeReference.  # noqa: E501
        :type: float
        """

        self._percentage = percentage

    @property
    def price(self):
        """Gets the price of this TimeseriesCrudeReference.  # noqa: E501


        :return: The price of this TimeseriesCrudeReference.  # noqa: E501
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this TimeseriesCrudeReference.


        :param price: The price of this TimeseriesCrudeReference.  # noqa: E501
        :type: float
        """

        self._price = price

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TimeseriesCrudeReference, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TimeseriesCrudeReference):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
