# coding: utf-8

"""
    Refinery Calc API Documentation

    Integrate the powerful Refinery Calc Engine into your process using this API.  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@refinerycalc.com.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UnitHealthStateRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'apply_all': 'bool',
        'health_state': 'HealthState'
    }

    attribute_map = {
        'apply_all': 'applyAll',
        'health_state': 'healthState'
    }

    def __init__(self, apply_all=None, health_state=None):  # noqa: E501
        """UnitHealthStateRequest - a model defined in Swagger"""  # noqa: E501
        self._apply_all = None
        self._health_state = None
        self.discriminator = None
        if apply_all is not None:
            self.apply_all = apply_all
        if health_state is not None:
            self.health_state = health_state

    @property
    def apply_all(self):
        """Gets the apply_all of this UnitHealthStateRequest.  # noqa: E501


        :return: The apply_all of this UnitHealthStateRequest.  # noqa: E501
        :rtype: bool
        """
        return self._apply_all

    @apply_all.setter
    def apply_all(self, apply_all):
        """Sets the apply_all of this UnitHealthStateRequest.


        :param apply_all: The apply_all of this UnitHealthStateRequest.  # noqa: E501
        :type: bool
        """

        self._apply_all = apply_all

    @property
    def health_state(self):
        """Gets the health_state of this UnitHealthStateRequest.  # noqa: E501


        :return: The health_state of this UnitHealthStateRequest.  # noqa: E501
        :rtype: HealthState
        """
        return self._health_state

    @health_state.setter
    def health_state(self, health_state):
        """Sets the health_state of this UnitHealthStateRequest.


        :param health_state: The health_state of this UnitHealthStateRequest.  # noqa: E501
        :type: HealthState
        """

        self._health_state = health_state

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UnitHealthStateRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UnitHealthStateRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
